dist: trusty
language: rust
cache: cargo
branches:
  only:
  - master
before_script:
  - cargo install mdbook --vers 0.2.3 --force
script:
  - bash ci/build.sh
after_script: []
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master