[book]
authors = ["RanolP"]
language = "en"
multilingual = false
src = "src"
title = "PSudo Guidebook"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/PSudoLang/book/tree/master/guide"
additional-js = ["../basis/book/psudo-highlight.js"]